version: "3"
services:

  mysql:
    image: mysql:5.7
    restart: always
    volumes:
      - db-data:/var/lib/mysql    
    ports:
      - 8086:3306
    environment:
      MYSQL_ROOT_PASSWORD: password123
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      MYSQL_ROOT_PASSWORD: password123
    links:
      - mysql:db
  web:
    image: wordpress
    volumes:
      - ./wordpress:/var/www/html
    restart: always
    links:
      - mysql
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: your_user
      WORDPRESS_DB_NAME: your_db_name
      WORDPRESS_DB_PASSWORD: your_pass            

## optional docker volumes for data
volumes:
 db-data: