version: "3"
services:

  mysql:
    image: mysql:5.7
    restart: always
    volumes:
      - ./data:/var/lib/mysql    
    ports:
      - 8086:3306
    environment:
      MYSQL_ROOT_PASSWORD: password123
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: password123 
  web:
    image: wordpress
    volumes:
      - ./wordpress:/var/www/html
    restart: always
    links:
      - mysql
    ports:
      - 8080:80      

## optional docker volumes for data
#volumes:
#  db-data: